### ISSUE TITLE
As the owner, I want to be able to use data from other websites, so I don't have to store the data myself 

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_BackEnd#1]
### Acceptance criteria
**Given**
* The frontend of the application is in a state where it needs to receive info/data (i.e. data about countries, events, weather)

**When**
* During normal use of the application, i.e when choosing country, date, city and when shown events and weather

**Then**
* The data should be fetched from the specified API's, and nothing relating to the view should be stored in a database

**Happy case**
All data is fetched and some is manipulated by the Java backend

**Bad case**
Data have to be stored in a database

### TASKS

- [x] (Runi - https://github.com/Hold-Krykke/3SemProject_BackEnd/pull/7) CI/pipeline setup and setup of codebase 
  - [x] no token or database-related code
  - [x] make sure no irrelevant files get copied over from the other startprojects (facadeExample, testExamples an so on)
  - [x] create a new gitignore file (only for the backend), only ignoring relevant things
- [x] (Camilla - #9 ) endpoint that can return data from ticketmaster api. Should take in date and location. Should handle a specific date and the case where no date is chosen (= all future dates) 
  - [x] ~~Create an EventFacade method that given a country-name returns an alpha-2 country code~~
- [x] (Malte - #10 ) endpoint + facade that returns 5 biggest cities from a specific european country + tests 
   - [x] Positive case test for REST endpoint. 
- [x] (Runi - #11 + #15 ) facade method that can return 5 biggest cities in each european country. This method will be called only on server startup. The returned data should be stored in an object/class.
- [x] ~~maybe and endpoint the returns the data from Chokobananen, unless we want the frontend to handle that.~~
- [x] (Asger - #12 ) Create an "alpha2"-endpoint and facade method that given an alpha-2 country code returns the full name of the country
   - [x] ( #14 )Fix Exception Handling
- [x] (Malte - #13 ) Test the "alpha2"-endpoint as well as its facade method
   - [x] Exception Test.

**Comment by MalteMagnussen** [comment]
>  maybe and endpoint the returns the data from Chokobananen, unless we want the frontend to handle that.

What would be the reasoning for making a proxy for their service? And not just direct calls?

**Comment by MrHardcode** [comment]
I think the idea is to make errorhandling in our own backend so we can send custom error messages to our frontend

**Comment by MalteMagnussen** [comment]
> I think the idea is to make errorhandling in our own backend so we can send custom error messages to our frontend

Wouldn't their backend have errorhandling as well, though?

**Comment by MrHardcode** [comment]
Yes, I suppose so. Maybe the task is unnecessary ¯\_(ツ)_/¯
