### ISSUE TITLE
[BUG] Current bugs

### ISSUE THREAD

**Issue by Runi-VN** [Hold-Krykke/3SemProject_BackEnd#19]
- [x] (Runi & Camilla https://github.com/Hold-Krykke/3SemProject_BackEnd/pull/28) UTF-8 Encoding Issue: #17 PR: ~~#18~~ #28 
- [x] (Runi - #21) ErrorHandling in CountryDTO.getSpecificCityByName() (exception)
- [ ] ~~Synchronization (?) for adding countries in CountryFacade~~
  - ~~Sometimes REST tests fail, as if the country list isn't populated.~~
- [ ] ~~France doesn't exist~~
  - ~~https://runivn.dk/3SEMPROJECT/api/resource/events?startdate=2019-12-03&enddate=2019-12-05&country=France&city=Paris~~
  - ~~If you check the `countries` list, `France` and `Paris` is actually there.~~
- [ ] ~~`countries` list hold countries with this format: `Paris` but if you search for `paris` an error is thrown.~~
  - ~~How do we wish to handle this, and how does Ticketmaster require data?~~
- [x] (Asger - #25) Document all error messages in Swagger
- [x] (Asger - #26) EventFacade.getApiData() checks for `response.page` but also needs to check for no. of elements at `response.page.totalElements`. If it is 0, there are 0 events available. (related to france issue above)
- [x] (Runi - #20) We exceed the [ticketmaster api rate limit](https://developer.ticketmaster.com/products-and-docs/apis/getting-started/#rate-limit) during our [REST tests](https://travis-ci.org/Hold-Krykke/3SemProject_BackEnd/jobs/616560998#L809). 
- [x] (Runi - https://github.com/Hold-Krykke/3SemProject_BackEnd/pull/22#discussion_r351532903) `EventFacade.java/getApiData()` does not handle usecases where requested data is not available, e.g. festivals vs. regular events.
- [x] (Runi - https://github.com/Hold-Krykke/3SemProject_BackEnd/pull/22#commits-pushed-29539ab) Swagger - https://i.imgur.com/8s1fKRV.png - Wrong URL. Should be `api/resource`
